#
# To build:
#
# Using multipass, one should enable a large multipass VM using:
#
#   SNAPCRAFT_BUILD_ENVIRONMENT_MEMORY=8G snapcraft
#
# Alternatively, one can build in a lxd container using:
#
#   snapcraft --use-lxd
#
# Install using something like:
#
#   sudo snap install --devmode bpftrace_0.9.4-20200312-1403-11814f2_amd64.snap
#
name: bpftrace
summary: high-level tracing language for Linux eBPF
description: BPFtrace is a high-level tracing language for
  Linux enhanced Berkeley Packet Filter available in recent
  Linux kernels. BPFtrace uses LLVM as a backend to compile scripts
  to BPF-bytecode and makes use of BCC for interacting with the Linux
  BPF system, as well as existing Linux tracing capabilities like
  kernel dynamic tracing, user-level dynamic tracing and tracepoints.

confinement: strict
grade: stable
base: core18
architectures: [amd64, arm64]
assumes: [snapd2.37]
adopt-info: bpftrace

parts:
    # Build LLVM from source to avoid: https://bugs.llvm.org/show_bug.cgi?id=44870
    llvm-11:
        plugin: nil
        build-packages:
            - git
            - devscripts
            - debhelper
            - cmake
            - chrpath 
            - texinfo 
            - sharutils 
            - libffi-dev 
            - libedit-dev 
            - libncurses5-dev 
            - swig 
            - python3-sphinx
            - binutils-dev
            - libjsoncpp-dev
            - pkg-config
            - lcov
            - help2man
            - zlib1g-dev
            - g++-multilib
            - libjs-mathjax
            - python3-recommonmark
            - doxygen
            - gfortran
            - ocaml-nox
            - ocaml-findlib
            - libctypes-ocaml-dev
            - dh-exec
            - dh-ocaml
            - libpfm4-dev
            - libz3-dev
            - libobjc-7-dev
        override-build: |
            git clone https://github.com/llvm/llvm-project -b llvmorg-11.0.0
            cd llvm-project/
            mkdir build
            cd build
            cmake ../llvm/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DLLVM_LIBDIR_SUFFIX=/usr/lib/x86_64-linux-gnu -DLLVM_INSTALL_BINUTILS_SYMLINKS=ON -DLLVM_INSTALL_CCTOOLS_SYMLINKS=ON -DLLVM_INCLUDE_TOOLS=ON -DLLVM_BUILD_TOOLS=ON -DLLVM_ENABLE_THREADS=ON -DLLVM_INCLUDE_TESTS=OFF -DLLVM_BUILD_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_BUILD_BENCHMARKS=OFF -DLLVM_ENABLE_ASSERTIONS=OFF -DLLVM_ENABLE_DOXYGEN=ON -DLLVM_BUILD_DOCS=ON -DLLVM_ENABLE_SPHINX=ON -DBUILD_SHARED_LIBS=OFF -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi"
            make install
    bcclibs3:
        after:
            - llvm-11
        source: https://github.com/iovisor/bcc.git
        source-tag: v0.17.0
        plugin: cmake
        configflags:
            - -DLLVM_DEFINITIONS="-D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS"
            - -DREVISION_LAST=v0.17.0
            - -DBCC_KERNEL_HAS_SOURCE_DIR=1
            - -DPYTHON_CMD='python2;python3'
            - -DCMAKE_BUILD_PARALLEL_LEVEL=1
            - -DCMAKE_INSTALL_PREFIX=/usr
        override-pull: |
          snapcraftctl pull
          sed -i "s;if os.environ.get('DESTDIR'):;if \"sdist\" not in sys.argv and os.environ.get('DESTDIR'):;" src/python/setup.py.in
        build-packages:
            - git
            - libc6
            - iperf
            - bison
            - cmake
            - flex
            - g++
            - binutils-dev
            - libstdc++-dev
            - libelf-dev
            - zlib1g-dev
            - libfl-dev
            - systemtap-sdt-dev
            - netperf
            - python3
            - arping
            - clang-format
            - ethtool
            - inetutils-ping
            - libedit-dev
            - libzip-dev
            - libluajit-5.1-dev
            - luajit
            - python3-netaddr
            - python3-pyroute2
            - python3-distutils
    libbpf:
        after:
            - bcclibs3
        plugin: nil
        override-build: |
            cd bcc/src/cc/libbpf/src
            sudo make install
            sudo ln -s /usr/include/bpf /usr/include/libbpf
    bpftrace:
        after:
            - libbpf
        source: https://github.com/iovisor/bpftrace.git
        source-tag: v0.11.4
        plugin: cmake
        configflags:
            - -DCMAKE_BUILD_TYPE=Release
            - -DLIBBCC_INCLUDE_DIRS=$SNAPCRAFT_STAGE/usr/include/bcc
        override-pull: |
            snapcraftctl pull
            description=$(git describe HEAD --tags)
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            version=$(echo $version$date-$commits-$sha | cut -c1-32)
            snapcraftctl set-version "$version"
        build-packages:
          - bison
          - cmake
          - flex
          - g++
          - git
          - libelf-dev
          - zlib1g-dev
          - libfl-dev
          - systemtap-sdt-dev
          - binutils-dev
        stage-packages:
          - libbinutils

apps:
    bpftrace:
        command: bpftrace
        plugs: [ home, system-trace ]

